include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    # Treat these as errors to prevent merging bad code
    missing_return: error
    dead_code: warning
    unused_import: warning
    unused_local_variable: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - ".dart_tool/**"

linter:
  rules:
    # ── Error Prevention ──
    avoid_print: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    
    # ── Style & Consistency ──
    always_declare_return_types: true
    always_use_package_imports: true
    annotate_overrides: true
    avoid_init_to_null: true
    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_single_quotes: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true
    
    # ── Async Safety ──
    unawaited_futures: true
    
    # ── Null Safety ──
    avoid_null_checks_in_equality_operators: true
    prefer_null_aware_operators: true
    prefer_if_null_operators: true
